name: Docker Image CI

on:
  workflow_dispatch:
  schedule:
  - cron: "0 2 * * *"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: docker run --rm -e repo=box_cust -e mirror=2 -e jar_suffix=css -e token=$ACCESS_TOKEN -e username=zhoujck -e num=1 -e url='https://framagit.org/zhoujck/config/-/raw/main/box&signame=糖果'  2011820123/tvbox
